version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
  app:
    container_name: cubank
    build:
      context: .
      target: development
    volumes:
      - /var/www/html
    ports:
      - 3000:80